services:
  db:
    image: postgres:14-bookworm
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgres/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  production:
    build:
      context: .
      target: production
    ports:
      - "8080:5000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - FLASK_APP=${FLASK_APP}
    depends_on:
      - db

  development:
    build:
      context: .
      target: development
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - FLASK_APP=${FLASK_APP}
      - FLASK_DEBUG=1
    env_file: ".env"
    depends_on:
      - db
    

volumes:
  db:
    driver: local
