services:
  db:
    image: postgres:14-bookworm
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgres/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    env_file: ".env"

  web:
    build: .
    ports:
      - "8080:5000"
    environment:
    - DATABASE_URL=${DATABASE_URL}
    - FLASK_APP=${FLASK_APP}
    env_file: ".env"
    depends_on:
      - db

volumes:
  db:
    driver: local
