"""empty message

Revision ID: 0363de7a2b26
Revises: 0f5365f565d4
Create Date: 2017-02-27 15:09:58.342845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0363de7a2b26'
down_revision = '0f5365f565d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('login', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'login')
    # ### end Alembic commands ###
