"""empty message

Revision ID: 1fe42e2c6db1
Revises: 0ebd770f791b
Create Date: 2016-06-13 10:35:26.885895

"""

# revision identifiers, used by Alembic.
revision = '1fe42e2c6db1'
down_revision = '0ebd770f791b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request', sa.Column('vendor_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'request', 'vendor', ['vendor_id'], ['id'])
    op.drop_constraint(u'vendor_request_id_fkey', 'vendor', type_='foreignkey')
    op.drop_column('vendor', 'request_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendor', sa.Column('request_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(u'vendor_request_id_fkey', 'vendor', 'request', ['request_id'], ['id'])
    op.drop_constraint(None, 'request', type_='foreignkey')
    op.drop_column('request', 'vendor_id')
    ### end Alembic commands ###
