"""Updated user to have first name, last name, division as enum

Revision ID: 21573c1bed5b
Revises: a511da9ef08c
Create Date: 2016-06-20 17:32:50.341335

"""

# revision identifiers, used by Alembic.
revision = '21573c1bed5b'
down_revision = 'a511da9ef08c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('first_name', sa.String(length=100), nullable=True))
    op.add_column('user', sa.Column('last_name', sa.String(length=100), nullable=True))
    op.drop_column('user', 'username')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'first_name')
    ### end Alembic commands ###
