"""empty message

Revision ID: 3299e15c0d1f
Revises: 75e16cd98c76
Create Date: 2017-03-31 11:08:43.946755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3299e15c0d1f'
down_revision = '75e16cd98c76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('request_id', sa.String(length=11), nullable=True))
    op.create_foreign_key(None, 'comment', 'request', ['request_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_column('comment', 'request_id')
    # ### end Alembic commands ###
