"""Added FK to Comment table for Request.ID

Revision ID: 333447794810
Revises: a283aa9213d7
Create Date: 2016-06-13 17:41:12.532926

"""

# revision identifiers, used by Alembic.
revision = '333447794810'
down_revision = 'a283aa9213d7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('request', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comment', 'request', ['request'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_column('comment', 'request')
    ### end Alembic commands ###
