"""Added user confirmation to user table

Revision ID: 3e98aaa168c8
Revises: d16b6ec9abdb
Create Date: 2016-06-21 01:18:57.273197

"""

# revision identifiers, used by Alembic.
revision = '3e98aaa168c8'
down_revision = 'd16b6ec9abdb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'confirmed')
    ### end Alembic commands ###
