"""Added grant_name and project_name columns to request table

Revision ID: 41248a6d8e0b
Revises: 7ca8572a872e
Create Date: 2016-06-20 10:57:10.749495

"""

# revision identifiers, used by Alembic.
revision = '41248a6d8e0b'
down_revision = '7ca8572a872e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request', sa.Column('grant_name', sa.String(length=100), nullable=True))
    op.add_column('request', sa.Column('project_name', sa.String(length=100), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('request', 'project_name')
    op.drop_column('request', 'grant_name')
    ### end Alembic commands ###
