"""Add division to Request

Revision ID: 5cedf53b8a3d
Revises: 21573c1bed5b
Create Date: 2016-06-20 17:54:41.462277

"""

# revision identifiers, used by Alembic.
revision = '5cedf53b8a3d'
down_revision = '21573c1bed5b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request', sa.Column('division', sa.String(length=100), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('request', 'division')
    ### end Alembic commands ###
