"""empty message

Revision ID: 75e16cd98c76
Revises: 2db3b661927b
Create Date: 2017-03-31 11:08:21.861356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75e16cd98c76'
down_revision = '2db3b661927b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('comment_request_id_fkey', 'comment', type_='foreignkey')
    op.drop_column('comment', 'request_id')
    op.alter_column('request', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=11),
               existing_server_default=sa.text("nextval('request_id_seq'::regclass)"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('request', 'id',
               existing_type=sa.String(length=11),
               type_=sa.INTEGER(),
               existing_server_default=sa.text("nextval('request_id_seq'::regclass)"))
    op.add_column('comment', sa.Column('request_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('comment_request_id_fkey', 'comment', 'request', ['request_id'], ['id'])
    # ### end Alembic commands ###
