"""empty message

Revision ID: 7ca8572a872e
Revises: 333447794810
Create Date: 2016-06-13 19:07:09.853215

"""

# revision identifiers, used by Alembic.
revision = '7ca8572a872e'
down_revision = '333447794810'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request', sa.Column('comment_id', sa.Integer(), nullable=True))
    op.add_column('request', sa.Column('creator_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'request', 'user', ['creator_id'], ['id'])
    op.create_foreign_key(None, 'request', 'comment', ['comment_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'request', type_='foreignkey')
    op.drop_constraint(None, 'request', type_='foreignkey')
    op.drop_column('request', 'creator_id')
    op.drop_column('request', 'comment_id')
    ### end Alembic commands ###
