"""create status_events table

Revision ID: 7cb1b3b52662
Revises: e27682eaa1b2
Create Date: 2024-04-25 12:21:07.901039

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '7cb1b3b52662'
down_revision = 'e27682eaa1b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('status_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('previous_value', sa.Enum('Needs Division Approval', 'Needs Commissioner Approval', 'Needs Procurement Head Approval', 'Approved - Pending', 'Order in Progress', 'Denied', 'Resolved', 'Hold', name='status'), nullable=True),
    sa.Column('new_value', sa.Enum('Needs Division Approval', 'Needs Commissioner Approval', 'Needs Procurement Head Approval', 'Approved - Pending', 'Order in Progress', 'Denied', 'Resolved', 'Hold', name='status'), nullable=True),
    sa.Column('request_id', sa.String(length=11), nullable=False),
    sa.Column('user_id', sa.Integer, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_user_email')
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.create_index('ix_user_email', ['email'], unique=True)

    op.drop_table('status_events')
    # ### end Alembic commands ###
