"""empty message

Revision ID: 97e547ef6354
Revises: 
Create Date: 2017-02-28 12:40:40.896537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97e547ef6354'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('request', 'name')
    op.add_column('user', sa.Column('is_admin', sa.BOOLEAN(), nullable=True))
    op.add_column('user', sa.Column('login', sa.BOOLEAN(), nullable=True))
    op.drop_column('user', 'role')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role', sa.VARCHAR(length=100), server_default=sa.text("'Regular User'::character varying"), autoincrement=False, nullable=False))
    op.drop_column('user', 'login')
    op.drop_column('user', 'is_admin')
    op.add_column('request', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
