"""Adding FK Relationships

Revision ID: a283aa9213d7
Revises: cc8fca3c23bc
Create Date: 2016-06-13 17:36:43.690810

"""

# revision identifiers, used by Alembic.
revision = 'a283aa9213d7'
down_revision = 'cc8fca3c23bc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('user', sa.Integer(), nullable=True))
    op.drop_constraint(u'comment_request_id_fkey', 'comment', type_='foreignkey')
    op.drop_constraint(u'comment_user_id_fkey', 'comment', type_='foreignkey')
    op.create_foreign_key(None, 'comment', 'user', ['user'], ['id'])
    op.drop_column('comment', 'user_id')
    op.drop_column('comment', 'request_id')
    op.drop_constraint(u'request_user_id_fkey', 'request', type_='foreignkey')
    op.drop_column('request', 'user_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(u'request_user_id_fkey', 'request', 'user', ['user_id'], ['id'])
    op.add_column('comment', sa.Column('request_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('comment', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.create_foreign_key(u'comment_user_id_fkey', 'comment', 'user', ['user_id'], ['id'])
    op.create_foreign_key(u'comment_request_id_fkey', 'comment', 'request', ['request_id'], ['id'])
    op.drop_column('comment', 'user')
    ### end Alembic commands ###
