"""empty message

Revision ID: bd25dda41a5f
Revises: bc0ea960bc66
Create Date: 2016-06-02 13:14:43.342155

"""

# revision identifiers, used by Alembic.
revision = 'bd25dda41a5f'
down_revision = 'bc0ea960bc66'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request', sa.Column('date_submitted', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('request', 'date_submitted')
    ### end Alembic commands ###
