"""empty message

Revision ID: cc8fca3c23bc
Revises: 1fe42e2c6db1
Create Date: 2016-06-13 14:36:18.681244

"""

# revision identifiers, used by Alembic.
revision = 'cc8fca3c23bc'
down_revision = '1fe42e2c6db1'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('filepath', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['request.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('note')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('note',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('request_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['request_id'], [u'request.id'], name=u'note_request_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], [u'users.id'], name=u'note_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name=u'note_pkey')
    )
    op.drop_table('comment')
    ### end Alembic commands ###
