"""empty message

Revision ID: e1672de2d7a4
Revises: 62eafb70058e
Create Date: 2017-03-16 14:30:58.152171

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e1672de2d7a4'
down_revision = '62eafb70058e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'division',
                    type_=sa.Enum('Records Management', 'Archives', 'Grants', 'Library', 'Executive', 'Tech',
                                  'Administration', name='division'),
                    existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'division',
                    existing_type=sa.Enum('Records Management', 'Archives', 'Grants', 'Library', 'Executive', 'Tech',
                                  'Administration', name='division'),
                    type_=postgresql.ENUM('Records Management', 'Archives', 'Grants', 'Library', 'Executive', 'MIS/Web',
                                          'Administration', name='division'),
                    existing_nullable=True)
    # ### end Alembic commands ###
