"""empty message

Revision ID: ea7dfd6b7643
Revises: 97e547ef6354
Create Date: 2017-02-28 13:39:42.914148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea7dfd6b7643'
down_revision = '97e547ef6354'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role', sa.String(length=100), nullable=True))
    op.drop_column('user', 'is_admin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_admin', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('user', 'role')
    # ### end Alembic commands ###
