"""empty message

Revision ID: f0bf9ad93a6d
Revises: 3299e15c0d1f
Create Date: 2017-04-25 15:51:00.232454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0bf9ad93a6d'
down_revision = '3299e15c0d1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendor', sa.Column('enabled', sa.Boolean(), nullable=False, server_default='true'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendor', 'enabled')
    # ### end Alembic commands ###
