"""Changed "Note" to "Comment" and added in fields

Revision ID: 54bdffeafe4f
Revises: 0ebd770f791b
Create Date: 2016-06-12 19:15:55.343950

"""

# revision identifiers, used by Alembic.
revision = '54bdffeafe4f'
down_revision = '0ebd770f791b'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('filepath', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['request.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('note')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('note',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('request_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['request.id'], name='note_request_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='note_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='note_pkey')
    )
    op.drop_table('comment')
    ### end Alembic commands ###
