"""Update FK Constraints

Revision ID: fb13ea831ad7
Revises: 626d6071278c
Create Date: 2016-06-13 16:44:23.494510

"""

# revision identifiers, used by Alembic.
revision = 'fb13ea831ad7'
down_revision = '626d6071278c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('users', 'user')
    op.execute('ALTER SEQUENCE  users_id_seq RENAME TO user_id_seq')
    op.execute('ALTER INDEX users_pkey RENAME TO user_pkey')
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.drop_table('users')
    op.drop_constraint('comment_user_id_fkey', 'comment', type_='foreignkey')
    op.create_foreign_key(None, 'comment', 'user', ['user_id'], ['id'])
    op.add_column('request', sa.Column('creator_id', sa.Integer(), nullable=True))
    op.add_column('request', sa.Column('vendor_id', sa.Integer(), nullable=True))
    op.drop_constraint('request_user_id_fkey', 'request', type_='foreignkey')
    op.create_foreign_key(None, 'request', 'vendor', ['vendor_id'], ['id'])
    op.create_foreign_key(None, 'request', 'user', ['creator_id'], ['id'])
    op.drop_column('request', 'user_id')
    op.alter_column('vendor', 'mwbe',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_constraint('vendor_request_id_fkey', 'vendor', type_='foreignkey')
    op.drop_column('vendor', 'request_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendor', sa.Column('request_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('vendor_request_id_fkey', 'vendor', 'request', ['request_id'], ['id'])
    op.alter_column('vendor', 'mwbe',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.add_column('request', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'request', type_='foreignkey')
    op.drop_constraint(None, 'request', type_='foreignkey')
    op.create_foreign_key('request_user_id_fkey', 'request', 'users', ['user_id'], ['id'])
    op.drop_column('request', 'vendor_id')
    op.drop_column('request', 'creator_id')
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.create_foreign_key('comment_user_id_fkey', 'comment', 'users', ['user_id'], ['id'])
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('division', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_pkey')
    )
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    ### end Alembic commands ###
